/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import SistemaImobiliaria.*;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Acer
 */
public class BuscaPorCidade extends javax.swing.JFrame {
    Funcoes app = new Funcoes();
    ArrayList <Imovel> v = new ArrayList <>();
    
    /**
     * Creates new form TelaLogin
     */
    public BuscaPorCidade() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FundoTelaLogin = new javax.swing.JPanel();
        BotaoEntrar = new javax.swing.JButton();
        EntradaDoUsuario = new javax.swing.JTextField();
        TituloParaDirecionarUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaImoveis = new javax.swing.JTable();
        BotaoMaisDetalhes = new javax.swing.JButton();
        BotaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busca por Cidade");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BotaoEntrar.setBackground(new java.awt.Color(0, 255, 127));
        BotaoEntrar.setText("Procurar");
        BotaoEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEntrarActionPerformed(evt);
            }
        });

        EntradaDoUsuario.setPreferredSize(new java.awt.Dimension(448, 22));
        EntradaDoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaDoUsuarioActionPerformed(evt);
            }
        });

        TituloParaDirecionarUsuario.setText("Digite a cidade que deseja pesquisar:");

        TabelaImoveis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelaImoveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "Valor", "Proprietario", "Cidade", "Bairro", "Rua", "Numero", "Nro Quartos", "Nro Banheiros"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaImoveis);

        BotaoMaisDetalhes.setBackground(new java.awt.Color(255, 165, 0));
        BotaoMaisDetalhes.setText("Mais Detalhes");
        BotaoMaisDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMaisDetalhesActionPerformed(evt);
            }
        });

        BotaoVoltar.setBackground(new java.awt.Color(255, 160, 122));
        BotaoVoltar.setText("Voltar");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FundoTelaLoginLayout = new javax.swing.GroupLayout(FundoTelaLogin);
        FundoTelaLogin.setLayout(FundoTelaLoginLayout);
        FundoTelaLoginLayout.setHorizontalGroup(
            FundoTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoTelaLoginLayout.createSequentialGroup()
                .addGroup(FundoTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FundoTelaLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FundoTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoTelaLoginLayout.createSequentialGroup()
                                .addComponent(TituloParaDirecionarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EntradaDoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoTelaLoginLayout.createSequentialGroup()
                                .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoMaisDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(FundoTelaLoginLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)))
                .addContainerGap())
        );
        FundoTelaLoginLayout.setVerticalGroup(
            FundoTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoTelaLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FundoTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloParaDirecionarUsuario)
                    .addComponent(EntradaDoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoEntrar))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FundoTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoMaisDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        EntradaDoUsuario.getAccessibleContext().setAccessibleName("Entrada do usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FundoTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FundoTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Funcao que detecta quando o botao de pesquisa eh pressionado
    private void BotaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEntrarActionPerformed
        //String chave da pesquisa
        String entrada = "";
        //Pegar o texto presente na caixa de texto
        entrada = EntradaDoUsuario.getText();
        ArrayList <Imovel> r = app.buscarCidade(v, entrada);
        //"Limpar" a tabela
        DefaultTableModel mp1 = (DefaultTableModel) TabelaImoveis.getModel();
        int l = mp1.getRowCount();
        if(l > 0){
            while(l>0){
                ((DefaultTableModel) TabelaImoveis.getModel()).removeRow(l-1);
                l--;
            }
        }
        //Formar nova tabela baseando-se nos elementos retornados na busca
        DefaultTableModel mp = (DefaultTableModel) TabelaImoveis.getModel();
        for(var E : r){
            //Adiciona um Imovel a tabela
            mp.addRow(new Object[]{E.getId(), E.getClass().getSimpleName(), E.getValor(), E.getProprietario(), E.getCidade(), E.getBairro(), E.getRua(), E.getNumero(), E.getQuartos(), E.getBanheiros()});
        }
        
    }//GEN-LAST:event_BotaoEntrarActionPerformed

    private void EntradaDoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaDoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaDoUsuarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tamanhoColuna();
        //Le o arquivo e armazena no ArrayList v
        app.lerArquivo(v);
        //"Limpa" a tabela
        DefaultTableModel mp1 = (DefaultTableModel) TabelaImoveis.getModel();
        int l = mp1.getRowCount();
        if(l > 0){
            while(l>0){
                ((DefaultTableModel) TabelaImoveis.getModel()).removeRow(l-1);
                l--;
            }
        }
        //Forma uma nova tabela baseada no vetor v
        DefaultTableModel mp = (DefaultTableModel) TabelaImoveis.getModel();
        for(var E : v){
            mp.addRow(new Object[]{E.getId(), E.getClass().getSimpleName(), E.getValor(), E.getProprietario(), E.getCidade(), E.getBairro(), E.getRua(), E.getNumero(), E.getQuartos(), E.getBanheiros()});
        }
        //Ordenar quando clickar em uma coluna
        TabelaImoveis.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_formWindowOpened

    private void BotaoMaisDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMaisDetalhesActionPerformed
        //Retorna a posiçao da linha selecionada. -1 se nenhuma linha for selecionada
        int i = TabelaImoveis.getSelectedRow();
        if(i == -1){
            //Mensagem de erro: Nenhuma linha selecionada
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela para ver mais detalhes do imovel!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //Pega o valor de id do imovel selecionado
            int id = (Integer) TabelaImoveis.getValueAt(i, 0);
            for(var E : v){
               //Acha o imovel selecionado pelo id
               if(E.getId() == id){
                    //Mostra as infos do imovel selecionado
                    new TelaMostraImovel(E).setVisible(true);
                    break;
                }
            }
        }
    }//GEN-LAST:event_BotaoMaisDetalhesActionPerformed

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        //Volta ao menu principal e fecha pagina atual
        new MenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed
    public void tamanhoColuna(){
        //Redimenciona tamanho minimo de algumas colunas
        TabelaImoveis.getColumnModel().getColumn(0).setMinWidth(25);
        TabelaImoveis.getColumnModel().getColumn(1).setMinWidth(125);
        TabelaImoveis.getColumnModel().getColumn(2).setMinWidth(50);
        TabelaImoveis.getColumnModel().getColumn(3).setMinWidth(125);
        TabelaImoveis.getColumnModel().getColumn(4).setMinWidth(75);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaPorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaPorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaPorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaPorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaPorCidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoEntrar;
    private javax.swing.JButton BotaoMaisDetalhes;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JTextField EntradaDoUsuario;
    private javax.swing.JPanel FundoTelaLogin;
    private javax.swing.JTable TabelaImoveis;
    private javax.swing.JLabel TituloParaDirecionarUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
