/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import SistemaImobiliaria.Funcoes;
import SistemaImobiliaria.Imovel;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Formatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private Funcoes app = new Funcoes();
    private ArrayList <Imovel> v = new ArrayList <>();
    private Formatter saida;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotaoBoolProp = new javax.swing.JButton();
        BotaoBuscaQuartos = new javax.swing.JButton();
        BotaoBuscaPorValor = new javax.swing.JButton();
        BotaoBuscaPorTipoDeImovel = new javax.swing.JButton();
        BotaoBuscaPorCidade = new javax.swing.JButton();
        BuscaImoveisPorProprietario = new javax.swing.JButton();
        Subtitulo = new javax.swing.JLabel();
        BotaoExportar = new javax.swing.JButton();
        Titulo1 = new javax.swing.JLabel();
        Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BotaoBoolProp.setText("Verificar Proprietario");
        BotaoBoolProp.setToolTipText("Verifica se certo proprietário se encontra no sistema da imobiliária.");
        BotaoBoolProp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoBoolProp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoBoolPropMouseEntered(evt);
            }
        });
        BotaoBoolProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVerificarPropActionPerformed(evt);
            }
        });

        BotaoBuscaQuartos.setText("Ver imoveis por número de quartos");
        BotaoBuscaQuartos.setToolTipText("Busca por imoveis com um número minimo de quartos");
        BotaoBuscaQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscaQuartosActionPerformed(evt);
            }
        });

        BotaoBuscaPorValor.setText("Ver imoveis abaixo de um valor ");
        BotaoBuscaPorValor.setToolTipText("Verifica a existencia de imoveis abaixo de um valor desejado.");
        BotaoBuscaPorValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoImoveisPorValorActionPerformed(evt);
            }
        });

        BotaoBuscaPorTipoDeImovel.setText("Ver imoveis por tipo e ordenados por um valor");
        BotaoBuscaPorTipoDeImovel.setToolTipText("Busca por imoveis por determinado tipo específico");
        BotaoBuscaPorTipoDeImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscaTipoActionPerformed(evt);
            }
        });

        BotaoBuscaPorCidade.setText("Ver imoveis localizados em uma cidade");
        BotaoBuscaPorCidade.setToolTipText("Busca por imovis em uma cidade específica");
        BotaoBuscaPorCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscaPorCidadeActionPerformed(evt);
            }
        });

        BuscaImoveisPorProprietario.setText("Ver imoveis por proprietario");
        BuscaImoveisPorProprietario.setToolTipText("Busca dos imoveis de um proprietário específico");
        BuscaImoveisPorProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscaImovelPorPropActionPerformed(evt);
            }
        });

        Subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitulo.setText("Selecione a opção desejada:");

        BotaoExportar.setText("Exportar lista de imoveis");
        BotaoExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExportarActionPerformed(evt);
            }
        });

        Titulo1.setBackground(new java.awt.Color(0, 0, 0));
        Titulo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("BEM VINDO AO MENU DE OPÇÕES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscaImoveisPorProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoBuscaPorCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoBuscaPorTipoDeImovel, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(BotaoBuscaQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoBuscaPorValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoBoolProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(BotaoBoolProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoBuscaPorValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoBuscaQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoBuscaPorTipoDeImovel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoBuscaPorCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuscaImoveisPorProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(122, 122, 122))
        );

        Sair.setBackground(new java.awt.Color(178, 34, 34));
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //botao para sair da tela de menu
    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    //botao que ira abrir nova tela para buscar por propriedade com quantidade de quartos 
    //maior ou igual a especificada pelo usuario
    private void BotaoBuscaQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscaQuartosActionPerformed
        new BuscaPorQuartos().setVisible(true);
        dispose();
    }//GEN-LAST:event_BotaoBuscaQuartosActionPerformed

    //botao que ira abrir nova tela para verificar o proprietario de um imovel
    private void BotaoVerificarPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVerificarPropActionPerformed
        String nome = JOptionPane.showInputDialog("Digite o nome do proprietario");
        if(!(nome == null)){
            boolean saida = app.buscaProprietario(v, nome);
            if(saida)
                //informa se o proprietario se encontra na lista ou nao
                JOptionPane.showMessageDialog(null, "O proprietario se encontra na lista", "Busca sucedida", JOptionPane.INFORMATION_MESSAGE);
            else{
                JOptionPane.showMessageDialog(null, "O proprietario nao se encontra na lista", "Busca sucedida", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BotaoVerificarPropActionPerformed

    private void BotaoBoolPropMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBoolPropMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoBoolPropMouseEntered

    //botao que ira abrir nova tela para verificar imoveis por valor
    private void BotaoImoveisPorValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoImoveisPorValorActionPerformed
        new BuscaPorValor().setVisible(true);
        dispose();
    }//GEN-LAST:event_BotaoImoveisPorValorActionPerformed

    //botao que ira abrir nova tela para buscar imoveis por tipo
    private void BotaoBuscaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscaTipoActionPerformed
        new BuscaPorTipo().setVisible(true);
        dispose();
    }//GEN-LAST:event_BotaoBuscaTipoActionPerformed

    //botao que ira abrir nova tela para buscar imoveis por cidade
    private void BotaoBuscaPorCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscaPorCidadeActionPerformed
        new BuscaPorCidade().setVisible(true);
        dispose();
    }//GEN-LAST:event_BotaoBuscaPorCidadeActionPerformed

    //botao que ira abrir nova tela para buscar imoveis por proprietario
    private void BotaoBuscaImovelPorPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscaImovelPorPropActionPerformed
        new BuscaPorProprietario().setVisible(true);
        dispose();
    }//GEN-LAST:event_BotaoBuscaImovelPorPropActionPerformed

    //funcao que le arquivo com os dados dos imoveis
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        app.lerArquivo(v);
    }//GEN-LAST:event_formWindowOpened

    //funcao que ira exportar um arquivo de saida
    private void BotaoExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExportarActionPerformed
        try {
            saida = new Formatter("saida.txt");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível criar arquivo de saida", "ERRO!", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        for(var E : v){
            saida.format(E.toString());
        }
        JOptionPane.showMessageDialog(null, "Arquivo criado com sucesso", "SUCESSO!", JOptionPane.INFORMATION_MESSAGE);
        saida.close();
    }//GEN-LAST:event_BotaoExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBoolProp;
    private javax.swing.JButton BotaoBuscaPorCidade;
    private javax.swing.JButton BotaoBuscaPorTipoDeImovel;
    private javax.swing.JButton BotaoBuscaPorValor;
    private javax.swing.JButton BotaoBuscaQuartos;
    private javax.swing.JButton BotaoExportar;
    private javax.swing.JButton BuscaImoveisPorProprietario;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
